Repository likelion-inha-hackathon-2/Summerthon-FE, pull requests merged in 2024-07, with the labels that each got.

#12 Feat: #5 회원가입 1,2 페이지 구현
  my-app/package-lock.json
  my-app/package.json
  my-app/public/index.html
  my-app/src/App.jsx
  my-app/src/components/Input/Input.jsx
  my-app/src/components/Radio/Radio.jsx
  my-app/src/hooks/useForm.jsx
  my-app/src/pages/Home.jsx
  my-app/src/pages/Login.jsx
  my-app/src/pages/Login_page.jsx
  my-app/src/pages/SignUpFirst.jsx
  my-app/src/pages/SignUpSecond.jsx
  my-app/webpack.config.js
Labels: 🔍 Refactor, 💡 feat

#15 header
  my-app/src/assets/icon.js
  my-app/src/pages/Header.jsx
  my-app/src/pages/HeaderS.jsx
  my-app/src/pages/Login.jsx
Labels: 💡 feat

#14 Feat: #10 메인 페이지 구현
  my-app/.gitignore
  my-app/public/index.html
  my-app/src/App.jsx
  my-app/src/assets/image.js
  my-app/src/assets/images/button-call.png
  my-app/src/assets/images/button-cancel.png
  my-app/src/assets/images/button-emer.png
  my-app/src/assets/images/button-scan.png
  my-app/src/components/Button/CancleButton.jsx
  my-app/src/components/Image/Image.jsx
  my-app/src/components/Map/Map.jsx
  my-app/src/components/Modal/Modal.jsx
  my-app/src/pages/Call.jsx
  my-app/src/pages/Login.jsx
  my-app/src/pages/Main.jsx
Labels: 💡 feat

#16 Refactor: #4 #5 #9 라우터 연결 및 페이지 리팩토링
  my-app/src/App.jsx
  my-app/src/pages/Header.jsx
  my-app/src/pages/HeaderS.jsx
  my-app/src/pages/Login.jsx
  my-app/src/pages/MyInfo.jsx
  my-app/src/pages/My_Info.jsx
  my-app/src/pages/SignUpSecond.jsx
  my-app/src/pages/Sign_up_page.jsx
Labels: 🔧 Fix, 🔍 Refactor

#18 Feat, Refactor: Swagger를 이용한 axios 연결, API 모듈화 및 리팩토링
  .github/workflows/main.yml
  my-app/package-lock.json
  my-app/package.json
  my-app/src/apis/authApi.js
  my-app/src/apis/kakaoApi.js
  my-app/src/apis/taxiApi.js
  my-app/src/components/Button/AddButton.jsx
  my-app/src/components/Button/Button.jsx
  my-app/src/components/Header/Header1.jsx
  my-app/src/components/Header/Header2.jsx
  my-app/src/components/Map/Map.jsx
  my-app/src/pages/Call.jsx
  my-app/src/pages/Header.jsx
  my-app/src/pages/HeaderS.jsx
  my-app/src/pages/Login.jsx
  my-app/src/pages/Main.jsx
  my-app/src/pages/MyInfo.jsx
  my-app/src/pages/SignUpFirst.jsx
  my-app/src/pages/SignUpSecond.jsx
  my-app/webpack.config.js
Labels: 🔍 Refactor, 💡 feat

#19 메인 페이지 도착지설정 라우팅
  my-app/src/App.jsx
  my-app/src/pages/Main.jsx
Labels: 🔧 Fix, 🔍 Refactor

#20 도착지설정 페이지
  my-app/src/pages/ArriveLocation.jsx
Labels: 💡 feat

#25 Fix, Refactor: 이메일 보내기 및 택시 호출 관련 부분 수정 중...
  my-app/src/apis/authApi.js
  my-app/src/apis/emailApi.js
  my-app/src/apis/kakaoApi.js
  my-app/src/apis/taxiApi.js
  my-app/src/components/Map/Map.jsx
  my-app/src/components/Taxi/Taxi.jsx
  my-app/src/pages/Call.jsx
  my-app/src/pages/EmerCall.jsx
  my-app/src/pages/Scan.jsx
Labels: 🔧 Fix, 🔍 Refactor

#26 Fix: 긴급 호출 시 보호자에게 이메일 보내기 테스트
  my-app/src/apis/authApi.js
  my-app/src/apis/emailApi.js
  my-app/src/pages/EmerCall.jsx
Labels: 🔧 Fix

#27 Fix: 의존성 배열 eslint 문제 해결 및 api 모듈 문서 수정 등
  my-app/src/apis/kakaoApi.js
  my-app/src/apis/taxiApi.js
  my-app/src/components/Modal/AddInfoModal.jsx
  my-app/src/components/Taxi/Taxi.jsx
  my-app/src/pages/Call.jsx
  my-app/src/pages/MyInfo.jsx
  my-app/src/pages/Scan.jsx
Labels: 🔧 Fix

#28 Refactor, Fix: #9 #10 #21 택시 호출 페이지 리팩토링 및 추가 등록 버그 수정
  my-app/src/App.jsx
  my-app/src/components/Button/AddButton.jsx
  my-app/src/components/Modal/AddAddressModal.jsx
  my-app/src/components/Modal/AddProtectorModal.jsx
  my-app/src/components/Taxi/Taxi.jsx
  my-app/src/pages/Call.jsx
  my-app/src/pages/MoreMyInfo.jsx
  my-app/src/pages/MyInfo.jsx
  my-app/src/pages/Scan.jsx
Labels: 🔧 Fix, 🔍 Refactor

#30 Refactor, Design: 반응형으로 Layout 수정
  my-app/public/index.html
  my-app/src/App.jsx
  my-app/src/assets/image.js
  my-app/src/assets/images/logo.png
  my-app/src/components/Button/AddButton.jsx
  my-app/src/components/Button/Button.jsx
  my-app/src/components/Button/CancleButton.jsx
  my-app/src/components/Container/Container.jsx
  my-app/src/components/Flex/Flex.jsx
  my-app/src/components/Header/Header1.jsx
  my-app/src/components/Header/Header2.jsx
  my-app/src/components/Input/Input.jsx
  my-app/src/components/Layout/Layout.jsx
  my-app/src/components/Map/Map.jsx
  my-app/src/components/Taxi/Taxi.jsx
  my-app/src/components/Typo/Typo.jsx
  my-app/src/pages/ArriveLocation.jsx
  my-app/src/pages/Call.jsx
  my-app/src/pages/EmerCall.jsx
  my-app/src/pages/Home.jsx
  my-app/src/pages/Login.jsx
  my-app/src/pages/Main.jsx
  my-app/src/pages/MoreMyInfo.jsx
  my-app/src/pages/MyInfo.jsx
  my-app/src/pages/Scan.jsx
  my-app/src/pages/SignUp.jsx
Labels: 🎨Desgin, 🔍 Refactor

#31 Chore: Delete .github/workflows directory
  .github/workflows/main.yml
Labels: documentation

#32 Fix: #29 모달 콘솔 에러 커스텀 속성으로 수정
  README.md
  my-app/src/components/Modal/Modal.jsx
  my-app/src/pages/MyInfo.jsx
Labels: 🔧 Fix

#34 Docs: 리드미 수정
  README.md
Labels: documentation
