Repository likelion-inha-hackathon-2/Summerthon-FE, pull requests merged in 2024-06, with the labels that each got.

#2 Chore: #1 Initial React App Setting
  my-app/.gitignore
  my-app/README.md
  my-app/package-lock.json
  my-app/package.json
  my-app/public/favicon.ico
  my-app/public/index.html
  my-app/public/manifest.json
  my-app/src/App.css
  my-app/src/App.js
  my-app/src/index.css
  my-app/src/index.js
Labels: 💡 feat

#6 Feat: #3 시작 페이지 만들기
  my-app/public/index.html
  my-app/public/manifest.json
  my-app/src/App.css
  my-app/src/App.js
  my-app/src/App.jsx
  my-app/src/assets/icon.js
  my-app/src/assets/icons/arrow.png
  my-app/src/assets/image.js
  my-app/src/assets/images/taxi.png
  my-app/src/assets/images/user.png
  my-app/src/components/Button/Button.jsx
  my-app/src/components/Container/Container.jsx
  my-app/src/components/Flex/Flex.jsx
  my-app/src/components/Image/Image.jsx
  my-app/src/components/Typo/Typo.jsx
  my-app/src/pages/StartPage.jsx
Labels: 💡 feat

#7 Chore: PR 템플릿 위치 변경
  .github/pull_request_template.md
Labels: documentation

#8 Refator: #3 페이지 이름 Home으로 변경
  my-app/src/App.jsx
  my-app/src/pages/Home.jsx
Labels: 🔍 Refactor

#11 Feat: #5 로그인 페이지 구현
  my-app/src/pages/Login_page.jsx
Labels: 💡 feat
